/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ClassInput = IDL.Record({
  'subject' : IDL.Text,
  'name' : IDL.Text,
});
export const ClassId = IDL.Nat;
export const Class = IDL.Record({
  'id' : ClassId,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'studentCount' : IDL.Nat,
});
export const Timestamp = IDL.Int;
export const StudentInput = IDL.Record({
  'name' : IDL.Text,
  'classId' : IDL.Opt(ClassId),
  'enrollmentDate' : Timestamp,
});
export const StudentId = IDL.Nat;
export const Student = IDL.Record({
  'id' : StudentId,
  'name' : IDL.Text,
  'classId' : IDL.Opt(ClassId),
  'enrollmentDate' : Timestamp,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const DashboardStats = IDL.Record({
  'totalClasses' : IDL.Nat,
  'averageClassSize' : IDL.Float64,
  'totalStudents' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createClass' : IDL.Func([ClassInput], [Class], []),
  'createStudent' : IDL.Func([StudentInput], [Student], []),
  'deleteClass' : IDL.Func([ClassId], [IDL.Bool], []),
  'deleteStudent' : IDL.Func([StudentId], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listClasses' : IDL.Func([], [IDL.Vec(Class)], ['query']),
  'listStudents' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(ClassId)],
      [IDL.Vec(Student)],
      ['query'],
    ),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'updateClass' : IDL.Func([ClassId, ClassInput], [IDL.Opt(Class)], []),
  'updateStudent' : IDL.Func([StudentId, StudentInput], [IDL.Opt(Student)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ClassInput = IDL.Record({ 'subject' : IDL.Text, 'name' : IDL.Text });
  const ClassId = IDL.Nat;
  const Class = IDL.Record({
    'id' : ClassId,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'studentCount' : IDL.Nat,
  });
  const Timestamp = IDL.Int;
  const StudentInput = IDL.Record({
    'name' : IDL.Text,
    'classId' : IDL.Opt(ClassId),
    'enrollmentDate' : Timestamp,
  });
  const StudentId = IDL.Nat;
  const Student = IDL.Record({
    'id' : StudentId,
    'name' : IDL.Text,
    'classId' : IDL.Opt(ClassId),
    'enrollmentDate' : Timestamp,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const DashboardStats = IDL.Record({
    'totalClasses' : IDL.Nat,
    'averageClassSize' : IDL.Float64,
    'totalStudents' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createClass' : IDL.Func([ClassInput], [Class], []),
    'createStudent' : IDL.Func([StudentInput], [Student], []),
    'deleteClass' : IDL.Func([ClassId], [IDL.Bool], []),
    'deleteStudent' : IDL.Func([StudentId], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listClasses' : IDL.Func([], [IDL.Vec(Class)], ['query']),
    'listStudents' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(ClassId)],
        [IDL.Vec(Student)],
        ['query'],
      ),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'updateClass' : IDL.Func([ClassId, ClassInput], [IDL.Opt(Class)], []),
    'updateStudent' : IDL.Func(
        [StudentId, StudentInput],
        [IDL.Opt(Student)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };