/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export interface Class {
  'id' : ClassId,
  'subject' : string,
  'name' : string,
  'studentCount' : bigint,
}
export type ClassId = bigint;
export interface ClassInput { 'subject' : string, 'name' : string }
export interface DashboardStats {
  'totalClasses' : bigint,
  'averageClassSize' : number,
  'totalStudents' : bigint,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface Student {
  'id' : StudentId,
  'name' : string,
  'classId' : [] | [ClassId],
  'enrollmentDate' : Timestamp,
}
export type StudentId = bigint;
export interface StudentInput {
  'name' : string,
  'classId' : [] | [ClassId],
  'enrollmentDate' : Timestamp,
}
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createClass' : ActorMethod<[ClassInput], Class>,
  'createStudent' : ActorMethod<[StudentInput], Student>,
  'deleteClass' : ActorMethod<[ClassId], boolean>,
  'deleteStudent' : ActorMethod<[StudentId], boolean>,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Returns the backend's public API documentation as Markdown.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listClasses' : ActorMethod<[], Array<Class>>,
  'listStudents' : ActorMethod<[[] | [string], [] | [ClassId]], Array<Student>>,
  'schema' : ActorMethod<[], string>,
  'updateClass' : ActorMethod<[ClassId, ClassInput], [] | [Class]>,
  'updateStudent' : ActorMethod<[StudentId, StudentInput], [] | [Student]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];